---
apiVersion: v1
kind: Config
clusters:
  - cluster:
      api-version: v1
      certificate-authority-data: ${rancher_cluster_ca}
      server: "${api_server_url}"
      # insecure-skip-tls-verify: true
    name: ${cluster_name}
contexts:
  - context:
      cluster: ${cluster_name}
      user: "kube-admin-rancher-management"
    name: ${cluster_name}
current-context: "rancher-management"
users:
  - name: "kube-admin-rancher-management"
    user:
      client-certificate-data: ${rancher_user_cert}
      client-key-data: ${rancher_user_key}